apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: chatapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: mauujo/chatapp-backend:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: chatapp-secrets
                  key: MONGO_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: chatapp-secrets
                  key: JWT_SECRET
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: chatapp-config
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: chatapp-config
                  key: PORT
            - name: AI_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: chatapp-config
                  key: AI_SERVICE_URL
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
