from typing import TypedDict, Annotated, Sequence
import operator
from langchain_core.messages import BaseMessage

class AgentState(TypedDict):
    # The list of messages in the current conversation thread
    messages: Annotated[Sequence[BaseMessage], operator.add]
    
    # The classified intent of the user's @ai command (e.g., "summarize", "draft", "qna")
    intent: str
    
    # The final output generated by the specialized agent to send back to Node.js
    final_response: str
    
    # Context data from the chat (like chat history or specific user data)
    chat_context: str