apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secrets
  namespace: chatapp
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://admin:mongo1234@chatapp.lxsm2zf.mongodb.net/chatapp?retryWrites=true&w=majority&appName=chatapp"
  JWT_SECRET: "mysecretkey12345"
  GEMINI_API_KEY: "AIzaSyBCvJ8DzK4yI7hOx6kuo-xHfbLYl0Bu8AU"
